# Default format properties for custom viz fixed_single_value.

display.visualizations.custom.splunk-one.fixed_single_value.sparkMin = 0
display.visualizations.custom.splunk-one.fixed_single_value.sparkMax = 100
display.visualizations.custom.splunk-one.fixed_single_value.goodColor = #01417F
display.visualizations.custom.splunk-one.fixed_single_value.badColor = #DFA611
display.visualizations.custom.splunk-one.fixed_single_value.textColor = #FFFFFF
display.visualizations.custom.splunk-one.fixed_single_value.sparkStroke = #FFFFFF
display.visualizations.custom.splunk-one.fixed_single_value.unit = %
