# Default format properties for custom viz fixed_loaded_line (React LineChart).

display.visualizations.custom.splunk-one.fixed_loaded_line.min = 0
display.visualizations.custom.splunk-one.fixed_loaded_line.max = 100
display.visualizations.custom.splunk-one.fixed_loaded_line.background = #0B1F3B
display.visualizations.custom.splunk-one.fixed_loaded_line.goodColor = #01417F
display.visualizations.custom.splunk-one.fixed_loaded_line.badColor = #DFA611
display.visualizations.custom.splunk-one.fixed_loaded_line.textColor = #FFFFFF
display.visualizations.custom.splunk-one.fixed_loaded_line.stroke = #FFFFFF
display.visualizations.custom.splunk-one.fixed_loaded_line.unit = %
display.visualizations.custom.splunk-one.fixed_loaded_line.smoothing = none
display.visualizations.custom.splunk-one.fixed_loaded_line.smaWindow = 3
display.visualizations.custom.splunk-one.fixed_loaded_line.maxPoints = 0
display.visualizations.custom.splunk-one.fixed_loaded_line.comparison = false
display.visualizations.custom.splunk-one.fixed_loaded_line.threshold = false
display.visualizations.custom.splunk-one.fixed_loaded_line.thresholdMin = 20
display.visualizations.custom.splunk-one.fixed_loaded_line.thresholdMax = 80
display.visualizations.custom.splunk-one.fixed_loaded_line.target = 50
display.visualizations.custom.splunk-one.fixed_loaded_line.anomalies = none
display.visualizations.custom.splunk-one.fixed_loaded_line.anomalySensitivity = 3
display.visualizations.custom.splunk-one.fixed_loaded_line.showXAxis = false
display.visualizations.custom.splunk-one.fixed_loaded_line.drilldown = false
display.visualizations.custom.splunk-one.fixed_loaded_line.drilldownQuery = "search index=_internal | stats count"

# Default format properties for custom viz line_single_value.

display.visualizations.custom.splunk-one.line_single_value.min = 0
display.visualizations.custom.splunk-one.line_single_value.max = 100
display.visualizations.custom.splunk-one.line_single_value.goodColor = #01417F
display.visualizations.custom.splunk-one.line_single_value.badColor = #DFA611
display.visualizations.custom.splunk-one.line_single_value.textColor = #FFFFFF
display.visualizations.custom.splunk-one.line_single_value.stroke = #FFFFFF
display.visualizations.custom.splunk-one.line_single_value.unit = %

# Default format properties for custom viz fixed_single_value.

display.visualizations.custom.splunk-one.fixed_single_value.sparkMin = 0
display.visualizations.custom.splunk-one.fixed_single_value.sparkMax = 100
display.visualizations.custom.splunk-one.fixed_single_value.goodColor = #01417F
display.visualizations.custom.splunk-one.fixed_single_value.badColor = #DFA611
display.visualizations.custom.splunk-one.fixed_single_value.textColor = #FFFFFF
display.visualizations.custom.splunk-one.fixed_single_value.sparkStroke = #FFFFFF
display.visualizations.custom.splunk-one.fixed_single_value.unit = %
